name: Radiation

main: com.seriousminecraft.Radiation.RadiationPlugin

version: 1.2

authors:
    - Kitteh

commands:
    radiation:
        description: Configure radiation regions
        usage: /radiation [add|set|delete] [RegionName]
    rad:
        description: Alias for radiation
        usage: /rad